name: build

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-targets:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux/386
          - linux/amd64
          - linux/arm
          - linux/arm64
          - linux/loong64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x
          - darwin/amd64
          - darwin/arm64
          - windows/386
          - windows/amd64
          - windows/arm
          - windows/arm64
          - freebsd/386
          - freebsd/amd64
          - freebsd/arm
          - freebsd/arm64
          - freebsd/riscv64
          - openbsd/386
          - openbsd/amd64
          - openbsd/arm
          - openbsd/arm64
          - netbsd/386
          - netbsd/amd64
          - netbsd/arm
          - netbsd/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build targets
        uses: zijiren233/go-build-action@v1
        env:
          SUBMICRO_ARM_DISABLED: true
          MICRO_ARM64_DISABLED: true
        with:
          targets: ${{ matrix.target }}
          enable-micro: true
          config-args: --skip-init-web

      - name: Get artifact name
        id: get_artifact_name
        run: |
          echo "ARTIFACT_NAME=$(echo ${{ matrix.target }} | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_artifact_name.outputs.ARTIFACT_NAME }}
          path: build/*
