name: release_dev

on:
  workflow_dispatch:

jobs:
  get-targets:
    name: Get all targets
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.get-targets.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get targets
        id: get-targets
        uses: zijiren233/go-build-action@v1
        with:
          show-all-targets: true

  release_dev:
    name: Release dev
    runs-on: ubuntu-latest
    needs: get-targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.get-targets.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build targets
        uses: zijiren233/go-build-action@v1
        with:
          targets: ${{ matrix.target }}
          enable-micro: ${{ !endsWith(matrix.target, '/arm64') }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          append_body: false
          fail_on_unmatched_files: true
          name: "Dev Build"
          tag_name: dev
          files: |
            build/*
