name: release_dev

on:
  workflow_dispatch:

jobs:
  release_dev:
    name: Release dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux/386
          - linux/amd64
          - linux/arm
          - linux/arm64
          - linux/loong64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x
          - linux/mips:cgo
          - linux/mips64:cgo
          - linux/mips64le:cgo
          - linux/mipsle:cgo
          - darwin/amd64
          - darwin/arm64
          - windows/386
          - windows/amd64
          - windows/arm64
          - freebsd/386
          - freebsd/amd64
          - freebsd/arm
          - freebsd/arm64
          - openbsd/amd64
          - openbsd/arm64
          - netbsd/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build targets
        uses: zijiren233/go-build-action@v1
        env:
          SUBMICRO_ARM_DISABLED: true
          MICRO_ARM64_DISABLED: true
        with:
          targets: ${{ matrix.target }}
          enable-micro: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          append_body: false
          fail_on_unmatched_files: true
          name: "Dev Build"
          tag_name: dev
          files: |
            build/*
